const countries = [
  "Afghanistan", 
  "Albania", 
  "Algeria", 
  "American Samoa", 
  "Andorra", 
  "Angola", 
  "Anguilla",
  "Antigua and Barbuda", 
  "Argentina", 
  "Armenia", 
  "Aruba", 
  "Australia", 
  "Austria", 
  "Azerbaijan", 
  "Bahamas", 
  "Bahrain", 
  "Bangladesh", 
  "Barbados", 
  "Belarus", 
  "Belgium", 
  "Belize", 
  "Benin", 
  "Bermuda", 
  "Bhutan", 
  "Bolivia", 
  "Bosnia and Herzegovina", 
  "Botswana", 
  "Bouvet Island", 
  "Brazil",
  "Brunei Darussalam", 
  "Bulgaria", 
  "Burkina Faso", 
  "Burundi", 
  "Cambodia", 
  "Cameroon", 
  "Canada", 
  "Cape Verde", 
  "Cayman Islands",
  "Chad", 
  "Chile", 
  "China",
  "Colombia",
  "Congo",
  "Costa Rica", 
  "Croatia", 
  "Cuba", 
  "Cyprus", 
  "Czech Republic", 
  "Denmark", 
  "Djibouti", 
  "Dominica", 
  "Dominican Republic",
  "Ecudaor", 
  "Egypt", 
  "El Salvador",
  "Estonia", 
  "Ethiopia",
  "Faroe Islands", 
  "Fiji", 
  "Finland", 
  "France",
  "French Guiana", 
  "French Polynesia",
  "Gabon", "Gambia", 
  "Georgia", "Germany", "Ghana", 
  "Gibraltar", "Greece", 
  "Greenland", 
  "Grenada", 
  "Guadeloupe", 
  "Guam", 
  "Guatemala",
  "Guyana", 
  "Haiti",
  "Honduras", 
  "Hong Kong", 
  "Hungary", 
  "Iceland", 
  "India", 
  "Indonesia",
  "Iraq", 
  "Ireland", 
  "Israel", 
  "Italy",
  "Jamaica", 
  "Japan", 
  "Jordan", 
  "Kazakhstan", 
  "Kenya",
  "Korea, Republic of",
  "Kuwait", 
  "Kyrgyzstan", 
  "Lao People's Democratic Republic", 
  "Latvia", 
  "Lebanon", 
  "Lesotho",
  "Libyan Arab Jamahiriya", 
  "Liechtenstein", 
  "Lithuania", 
  "Luxembourg",
  "Macedonia", 
  "Madagascar", 
  "Malawi", 
  "Malaysia", 
  "Maldives", 
  "Mali", 
  "Malta",
  "Martinique", 
  "Mauritania", 
  "Mauritius", 
  "Mayotte", 
  "Mexico", 
  "Micronesia, Federated States of", 
  "Moldova", 
  "Monaco", 
  "Mongolia",
  "Morocco", 
  "Mozambique", 
  "Myanmar", 
  "Namibia",
  "Nepal", 
  "Netherlands", 
  "Netherlands Antilles", 
  "New Caledonia", 
  "New Zealand", 
  "Nicaragua",
  "Nigeria",
  "Northern Mariana Islands", 
  "Norway", 
  "Oman", 
  "Pakistan", 
  "Palau", 
  "Panama",
  "Paraguay", 
  "Peru", 
  "Philippines",
  "Poland", 
  "Portugal", 
  "Puerto Rico", 
  "Qatar", 
  "Reunion", 
  "Romania", 
  "Russian Federation", 
  "Rwanda", 
  "Saint Kitts and Nevis", 
  "Saint Lucia", 
  "Saint Vincent and the Grenadines", 
  "Samoa", 
  "San Marino",
  "Saudi Arabia", 
  "Senegal", 
  "Seychelles",
  "Singapore", 
  "Slovakia", 
  "Slovenia", 
  "Solomon Islands",
  "South Africa",
  "Spain",
  "Sri Lanka",
  "Sudan", 
  "Suriname",
  "Swaziland", 
  "Sweden", 
  "Switzerland", 
  "Syrian Arab Republic", 
  "Taiwan", 
  "Tajikistan", 
  "Tanzania, United Republic of", 
  "Thailand", 
  "Togo",
  "Tonga", 
  "Trinidad and Tobago", 
  "Tunisia", 
  "Turkey", 
  "Turkmenistan",
  "Uganda", 
  "Ukraine", 
  "United Arab Emirates", 
  "United Kingdom", 
  "United States",
  "Uruguay", 
  "Uzbekistan", 
  "Vanuatu",
  "Venezuela",
  "Yemen",
  "Zambia", 
  "Zimbabwe"
]

export default countries;